name: Selenoid Tests Workflow

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-xdist allure-pytest

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Prepare Selenoid config
      run: |
        mkdir -p selenoid
        echo '{
          "chrome": {
            "default": "128.0",
            "versions": {
              "128.0": {
                "image": "selenoid/chrome:128.0",
                "port": "4444",
                "path": "/"
              }
            }
          }
        }' > selenoid/browsers.json

    - name: Start Selenoid
      run: |
        docker run -d --name selenoid \
          -p 4444:4444 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/selenoid:/etc/selenoid \
          aerokube/selenoid:latest-release \
          -limit 5
        
        echo "Waiting for Selenoid to start..."
        sleep 10
        curl http://localhost:4444/status

    - name: Run tests
      run: |
        python -m pytest --alluredir=allure-results -v
      env:
        SELENOID_URL: http://localhost:4444/wd/hub

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: allure-results/