name: Selenoid Tests Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
      
    - name: Create Selenoid config
      run: |
        mkdir -p selenoid
        echo '{
          "chrome": {
            "default": "128.0",
            "versions": {
              "128.0": {
                "image": "selenoid/chrome:128.0",
                "port": "4444",
                "path": "/"
              }
            }
          }
        }' > selenoid/browsers.json
        
        echo '{
          "videoOutputDir": "/tmp/video",
          "logOutputDir": "/tmp/logs"
        }' > selenoid/config.json
        
        chmod -R 755 selenoid
        
    - name: Pull Docker images
      run: |
        docker pull aerokube/selenoid:latest-release
        docker pull selenoid/chrome:128.0
        
    - name: Start Selenoid
      run: |
        docker run -d --name selenoid \
          -p 4444:4444 \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -v $(pwd)/selenoid:/etc/selenoid \
          -e OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/video \
          aerokube/selenoid:latest-release \
          -limit 5 -timeout 5m
        
        echo "Waiting for Selenoid to start..."
        for i in {1..30}; do
          if curl -s http://localhost:4444/status | grep -q '"total":1'; then
            echo "Selenoid is ready!"
            exit 0
          fi
          echo "Attempt $i/30: Selenoid not ready yet..."
          sleep 5
        done
        echo "Selenoid failed to start after 30 attempts"
        docker logs selenoid || true
        exit 1
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest --alluredir=allure-results -v
      env:
        SELENOID_URL: http://localhost:4444/wd/hub
        
    - name: Upload results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          allure-results/
          selenoid/
          
    - name: Clean up
      if: always()
      run: |
        docker stop selenoid || true
        docker rm selenoid || true